// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-[40vh] flex flex-col justify-center px-4\"><h2 class=\"text-2xl mb-8\">Laadukasta taksipalvelua Pudasjärven alueella</h2></div><section class=\"bg-slate-200 section\"><h2 class=\"text-2xl mb-2\">Tilaa taksi</h2><div><h3 class=\"\">Pudasjärven keskusta</h3><a href=\"tel:0400289760\" target=\"_blank\" rel=\"noopener noreferrer\">0400 289 760</a></div><div><h3 class=\"\">Jaurakkajärvi, Puhos, Ervasti</h3><a href=\"tel:0400386188\" target=\"_blank\" rel=\"noopener noreferrer\">0400 386 188</a></div><a href=\"/hinnasto\" target=\"_blank\" rel=\"noopener noreferrer\">tai tutustu hinnastoomme</a></section><section class=\"section\"><h2 class=\"text-2xl\">Pudasjärven Taksimatkat Oy</h2><p>Tarjoamme sinulle laadukkaita taksimatkoja Pudasjärven alueella jo yli 25 vuoden kokemuksella.</p><p>Sinua palvelee ammattitaitoinen henkilökuntamme kaikissa kuljetustehtävissä.</p><p>Olemme Suomen Taksiliiton jäseniä.</p></section><section class=\"section bg-slate-200\"><h2 class=\"text-2xl\">Palvelumme</h2><ol><li>Taksi</li><li>Kela-taksi Pudasjärvi</li><li>Tilausajot</li><li>Perusturva-ajot Pudasjärvi</li><li>Sopimuskuljetukset</li></ol><a href=\"/palvelut\">Lue lisää palveluistamme</a></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Pudasjärven Taksimatkat").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
